/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuloCarbon.View2;

/**
 *
 * @author wrivas
 */
public class MatrizDistribucion extends javax.swing.JPanel {

    /**
     * Creates new form MatrizDistribucion
     */
    public MatrizDistribucion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
/**
   SELECT distinct [me_cliente_cdgo] , SUM (CONVERT (decimal(38,2), REPLACE([me_costo_total],',','.'))) AS total --CONVERT (decimal(20,4), [me_costo_total]) 
  FROM [costos_vg].[dbo].[mvto_equipo]
WHERE [me_fecha_hora_inicio] BETWEEN '2021-04-01 00:00:00.000' AND '2021-04-30 23:59:00.000' 
 -- GROUP BY [me_cntro_cost_auxiliar_cdgo] 
 
 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
